### ISSUE TITLE
Allow specifying "icon" for Nano S+/X

### ISSUE THREAD

**Issue by dfordivam** [LedgerHQ/cargo-ledger#11]
The S+/X devices have a different icon than S, so it would be nice to somehow specify it in the Cargo.toml.
Perhaps optional fields like "icon-nanos", "icon-nanosplus", "icon-nanox", could be supported which will override the default "icon" and still maintain backward compatibility

**Comment by yhql** [comment]
Ah thanks for this issue, had it in the back of my mind! Is the provided PR OK for you?

**Comment by dfordivam** [comment]
Hi @yhql , Confirmed that it works
